import Head from 'next/head'
import { useRouter } from 'next/router'


export default function Sites() {
  const router = useRouter()
  const { all } = router.query
  console.log(router)
  

  return (
    <div>
      <Head>
        <title>About  / company Sites page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="title" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <div>
         this is hero page
      </div>
      <div style={{display:'flex'}}>
        {all?.length ? all.map((a , index)=>{
            return (
                <div key={index}>
                    {a} /
                </div>
            )
        }) : ''}
      </div>
    </div>
  )
}
