import Head from 'next/head'
import { useRouter } from 'next/router'


export default function Sites() {
  const router = useRouter()
  const { id } = router.query
  console.log(router)

//   router.push('/')

  return (
    <div>
      <Head>
        <title>About  / company Sites page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="title" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <div>
          About company Sites page with {id}
      </div>
    
    </div>
  )
}
