import Head from 'next/head'


export default function Sites() {
  return (
    <div>
      <Head>
        <title>About  / company Sites page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="title" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <div>
          About company Sites page
      </div>
    
    </div>
  )
}
