import Head from 'next/head'


export default function Ilham() {
  return (
    <div>
      <Head>
        <title>İlham  / company page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="title" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <div>
         İlham page
      </div>
    
    </div>
  )
}
